FROM python:3.11-slim

WORKDIR /app

# Increase pip timeout
ENV PIP_DEFAULT_TIMEOUT=300

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Install with increased timeout and retries
RUN pip install --no-cache-dir --default-timeout=300 --retries 5 -r requirements.txt

COPY src/ ./src/
COPY config/ ./config/

ENV PYTHONPATH=/app

CMD ["python", "src/producer/stock_producer.py"]
