#!/bin/bash
echo "╔════════════════════════════════════════════════╗"
echo "║  PHASE 2 - STEP 1 VERIFICATION                ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
echo "🐳 Docker Containers:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "NAME|kafka|zookeeper"
echo ""
echo "📡 Kafka Status:"
docker exec kafka kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1 && echo "   ✅ Kafka is responsive" || echo "   ❌ Kafka not ready"
echo ""
echo "📁 Configuration Files:"
[ -f docker-compose.yml ] && echo "   ✅ docker-compose.yml" || echo "   ❌ docker-compose.yml missing"
[ -f config/kafka_config.py ] && echo "   ✅ kafka_config.py" || echo "   ❌ kafka_config.py missing"
echo ""
echo "🌐 Web Interfaces:"
echo "   • Kafka UI: http://localhost:8080"
echo ""
echo "✅ Ready for Step 2: Building Stock Producer!"
