#!/bin/bash
echo "╔════════════════════════════════════════════════════════╗"
echo "║      PHASE 6 - CONTAINERIZATION VERIFICATION           ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "🐳 Docker Containers:"
docker-compose ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"
echo ""
echo "📊 Check Data Flow:"
echo "   1. Producer logs:"
docker-compose logs --tail=5 producer | grep "Fetched"
echo ""
echo "   2. Spark logs:"
docker-compose logs --tail=5 spark-processor | grep "Batch"
echo ""
echo "   3. PostgreSQL records:"
docker exec postgres psql -U stockuser -d stockmarket -c "SELECT COUNT(*) as total FROM stock_prices;" 2>/dev/null
echo ""
echo "🌐 Access Points:"
echo "   • Dashboard: http://localhost:8501"
echo "   • Kafka UI:  http://localhost:8080"
echo "   • pgAdmin:   http://localhost:5050"
echo ""
echo "✅ Phase 6 Complete!"
