#!/bin/bash
echo "╔══════════════════════════════════════════════════════════╗"
echo "║          PHASE 1 COMPLETE - FINAL VERIFICATION           ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "🖥️  System Information:"
echo "    • macOS: $(sw_vers -productVersion)"
echo "    • Architecture: $(uname -m)"
echo "    • User: $(whoami)"
echo "    • Disk Available: $(df -h ~ | tail -1 | awk '{print $4}')"
echo ""
echo "🍺 Homebrew:"
echo "    • $(brew --version | head -1)"
echo ""
echo "🐍 Python Environment:"
echo "    • Version: $(python --version)"
echo "    • Python3: $(python3 --version)"
echo "    • Location: $(which python)"
echo "    • Venv Active: $([ -n "$VIRTUAL_ENV" ] && echo '✅ YES' || echo '❌ NO')"
echo "    • Venv Path: $VIRTUAL_ENV"
echo "    • Total Packages: $(pip list | wc -l | tr -d ' ')"
echo ""
echo "🐳 Docker:"
echo "    • Version: $(docker --version)"
echo "    • Compose: $(docker-compose --version)"
echo "    • Status: $(docker info > /dev/null 2>&1 && echo '✅ Running' || echo '❌ Not running')"
echo ""
echo "📦 Critical Packages:"
pip list | grep -E "yfinance|kafka-python|pyspark|streamlit|redis|psycopg2" | awk '{printf "    • %-25s %s\n", $1, $2}'
echo ""
echo "📁 Project Structure:"
echo "    • Location: $(pwd)"
echo "    • Directories: $(find . -type d -not -path '*/venv/*' -not -path '*/.git/*' | wc -l | tr -d ' ')"
echo "    • Python Files: $(find . -name '*.py' -not -path '*/venv/*' | wc -l | tr -d ' ')"
echo "    • Git Initialized: $(git rev-parse --git-dir > /dev/null 2>&1 && echo '✅ YES' || echo '❌ NO')"
echo "    • Total Commits: $(git rev-list --count HEAD 2>/dev/null || echo '0')"
echo ""
echo "💻 VS Code:"
echo "    • Settings File: $([ -f .vscode/settings.json ] && echo '✅ Exists' || echo '❌ Missing')"
echo "    • Requirements: $([ -f requirements.txt ] && echo '✅ Exists' || echo '❌ Missing')"
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║     🎉 PHASE 1 COMPLETE - READY FOR KAFKA SETUP! 🚀     ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "📊 Phase 1 Achievements:"
echo "    ✅ Mac M2 environment configured"
echo "    ✅ Python 3.11.14 + 71 packages installed"
echo "    ✅ Docker Desktop running"
echo "    ✅ Complete project structure created"
echo "    ✅ Git repository with initial commit"
echo "    ✅ VS Code workspace ready"
echo ""
echo "🚀 Next Steps (Phase 2):"
echo "    1. Setup Apache Kafka with Docker Compose"
echo "    2. Build stock data producer"
echo "    3. Test with live Yahoo Finance data"
echo "    4. Implement error handling & logging"
echo "    5. Write Medium blog post #2"
echo ""
echo "⏱️  Estimated time for Phase 2: 4-6 hours over 2-3 days"
echo ""
