#!/bin/bash
echo "╔════════════════════════════════════════════════╗"
echo "║     PHASE 3 VERIFICATION - COMPLETE            ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
echo "✅ Finnhub Producer:"
grep -q "FINNHUB_API_KEY" src/producer/stock_producer.py && echo "   ✅ Finnhub integration" || echo "   ❌ Missing"
echo ""
echo "✅ Spark Processor:"
grep -q "calculate_moving_averages" src/processing/spark_processor.py && echo "   ✅ Window aggregations" || echo "   ❌ Missing"
grep -q "process_with_analytics" src/processing/spark_processor.py && echo "   ✅ Analytics mode" || echo "   ❌ Missing"
echo ""
echo "✅ Git Repository:"
git log --oneline -1
echo ""
echo "╔════════════════════════════════════════════════╗"
echo "║  ✅ PHASE 3 COMPLETE - READY FOR PHASE 4! 🚀  ║"
echo "╚════════════════════════════════════════════════╝"
