#!/bin/bash
echo "╔════════════════════════════════════════════════╗"
echo "║  PHASE 4 - CHECKPOINT 1: Infrastructure       ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
echo "🐳 Docker Containers:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "NAME|postgres|redis|kafka"
echo ""
echo "🐘 PostgreSQL:"
docker exec postgres psql -U stockuser -d stockmarket -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public';" 2>/dev/null && echo "   ✅ Database accessible" || echo "   ❌ Database not accessible"
echo ""
echo "🔴 Redis:"
docker exec redis redis-cli ping 2>/dev/null && echo "   ✅ Redis responsive" || echo "   ❌ Redis not responding"
echo ""
echo "📝 Configuration Files:"
[ -f config/db_config.py ] && echo "   ✅ db_config.py" || echo "   ❌ Missing"
[ -f scripts/init_db.sql ] && echo "   ✅ init_db.sql" || echo "   ❌ Missing"
echo ""
echo "✅ Ready for Step 2: Spark → PostgreSQL Integration"
